//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.12.09 at 04:19:20 PM GMT 
//


package ie.gmit.sw.model;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ie.gmit.sw.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements Serializable{

    private final static QName _Comment_QNAME = new QName("http://sw.gmit.ie/model/", "comment");
    private final static QName _RentalOrder_QNAME = new QName("http://sw.gmit.ie/model/", "rentalOrder");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ie.gmit.sw.model
     * 
     */
    public ObjectFactory() {
    }
    

    /**
     * Create an instance of {@link RentalOrder }
     * 
     */
    public RentalOrder createRentalOrder() {
        return new RentalOrder();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://sw.gmit.ie/model/", name = "comment")
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RentalOrder }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RentalOrder }{@code >}
     */
    @XmlElementDecl(namespace = "http://sw.gmit.ie/model/", name = "rentalOrder")
    public JAXBElement<RentalOrder> createRentalOrder(RentalOrder value) {
        return new JAXBElement<RentalOrder>(_RentalOrder_QNAME, RentalOrder.class, null, value);
    }

}
