//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.13 at 12:39:40 PM GMT 
//


package ie.gmit.sw.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Vehicle complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Vehicle"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vehiclePlate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="availableIndicator" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="vehicle_SID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Vehicle", namespace = "http://sw.gmit.ie/ds/", propOrder = {
    "vehiclePlate",
    "availableIndicator",
    "model"
})
public class Vehicle {

    @XmlElement(namespace = "http://sw.gmit.ie/ds/", required = true)
    protected String vehiclePlate;
    @XmlElement(namespace = "http://sw.gmit.ie/ds/")
    protected int availableIndicator;
    @XmlElement(namespace = "http://sw.gmit.ie/ds/", required = true)
    protected String model;
    @XmlAttribute(name = "vehicle_SID")
    protected String vehicleSID;

    /**
     * Gets the value of the vehiclePlate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehiclePlate() {
        return vehiclePlate;
    }

    /**
     * Sets the value of the vehiclePlate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehiclePlate(String value) {
        this.vehiclePlate = value;
    }

    /**
     * Gets the value of the availableIndicator property.
     * 
     */
    public int getAvailableIndicator() {
        return availableIndicator;
    }

    /**
     * Sets the value of the availableIndicator property.
     * 
     */
    public void setAvailableIndicator(int value) {
        this.availableIndicator = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the vehicleSID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleSID() {
        return vehicleSID;
    }

    /**
     * Sets the value of the vehicleSID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleSID(String value) {
        this.vehicleSID = value;
    }

}
